spring:
  datasource:
    url: ${{ secrets.ORACLE_URL }}
    username: ${{ secrets.ORACLE_USERNAME }}
    password: ${{ secrets.ORACLE_PASSWORD }}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    redis:
      host: localhost
      port: 6379

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secretKey: ${{ secrets.JWT_SECRET }}

kakao:
  rest-api-key: ${{ secrets.REST_API_KEY }}
  login-uri: http://localhost:8080/kakao
  logout-uri: http://localhost:8080/kakao/logout
